# Generated by Django 2.0.2 on 2019-01-15 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dat',
        ),
    ]
