# Generated by Django 2.0.2 on 2019-01-15 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_student_dat'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dat',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
