# Generated by Django 2.0.2 on 2019-01-15 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_student_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
